// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new1 controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PostController from "./post_controller"
application.register("post", PostController)
