default: &default
    adapter: postgresql
    encoding: unicode
    host: <%= ENV['POSTGRES_HOST'] %>
    min_messages: warning
    port: <%= ENV['POSTGRES_PORT'] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production: &production
    <<: *default
    database: <%= ENV['RDS_DB_NAME'] %>
    username: <%= ENV['RDS_USERNAME'] %>
    password: <%= ENV['RDS_PASSWORD'] %>
    host: <%= ENV['RDS_HOSTNAME'] %>
    port: <%= ENV['RDS_PORT'] %>


development:
    <<: *default
    database: <%= ENV['POSTGRES_DB'] %>
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    host: <%= ENV['POSTGRES_HOST'] %>
    port: <%= ENV['POSTGRES_PORT'] %>

test:
    <<: *default
    database: anticipation_test
    username: postgres
    password: postgres

staging:
    <<: *default
    database: <%= ENV['RDS_DB_NAME'] %>
    username: <%= ENV['RDS_USERNAME'] %>
    password: <%= ENV['RDS_PASSWORD'] %>
    host: <%= ENV['RDS_HOSTNAME'] %>
    port: <%= ENV['RDS_PORT'] %>

training:
    <<: *production