default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>


development_a:
    <<: *default
    database: ror7_blog
    username: postgres
    password: postgres
    host: db
    port: 5432

test:
  <<: *default
  database: railsondocker_test

production:
  <<: *default
  # url: <%= ENV['DATABASE_URL'] %>
  url: <%= ENV['DATABASE_URL_3'] %>
